/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Formation
 */
public class AirportsView extends javax.swing.JPanel {

    /**
     * Creates new form AirportsView
     */
    public AirportsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jp_tabAirport = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAirport = new javax.swing.JTable();
        jp_updateTabAirport = new javax.swing.JPanel();
        jl_city = new javax.swing.JLabel();
        jl_country = new javax.swing.JLabel();
        jt_city = new javax.swing.JTextField();
        jt_country = new javax.swing.JTextField();
        pb_reset = new javax.swing.JButton();
        pb_delete = new javax.swing.JButton();
        jl_aita = new javax.swing.JLabel();
        jt_aita = new javax.swing.JTextField();
        pb_update = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(2, 1));

        jp_tabAirport.setLayout(new java.awt.GridLayout());

        jTableAirport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "code AITA", "ville", "pays"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAirport);
        if (jTableAirport.getColumnModel().getColumnCount() > 0) {
            jTableAirport.getColumnModel().getColumn(0).setResizable(false);
            jTableAirport.getColumnModel().getColumn(1).setResizable(false);
            jTableAirport.getColumnModel().getColumn(2).setResizable(false);
        }

        jp_tabAirport.add(jScrollPane1);

        add(jp_tabAirport);

        jp_updateTabAirport.setLayout(new java.awt.GridBagLayout());

        jl_city.setText("ville");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jp_updateTabAirport.add(jl_city, gridBagConstraints);

        jl_country.setText("pays");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jp_updateTabAirport.add(jl_country, gridBagConstraints);

        jt_city.setPreferredSize(new java.awt.Dimension(150, 24));
        jt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_cityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        jp_updateTabAirport.add(jt_city, gridBagConstraints);

        jt_country.setPreferredSize(new java.awt.Dimension(150, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        jp_updateTabAirport.add(jt_country, gridBagConstraints);

        pb_reset.setText("réinitialiser");
        pb_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb_resetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        jp_updateTabAirport.add(pb_reset, gridBagConstraints);

        pb_delete.setText("supprimer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        jp_updateTabAirport.add(pb_delete, gridBagConstraints);

        jl_aita.setText("Aita");
        jp_updateTabAirport.add(jl_aita, new java.awt.GridBagConstraints());

        jt_aita.setPreferredSize(new java.awt.Dimension(150, 24));
        jt_aita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_aitaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        jp_updateTabAirport.add(jt_aita, gridBagConstraints);

        pb_update.setText("mettre à jour");
        pb_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb_updateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 8, 10);
        jp_updateTabAirport.add(pb_update, gridBagConstraints);

        add(jp_updateTabAirport);
    }// </editor-fold>//GEN-END:initComponents

    private void jt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_cityActionPerformed

    private void jt_aitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_aitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_aitaActionPerformed

    private void pb_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pb_resetActionPerformed

    private void pb_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pb_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAirport;
    private javax.swing.JLabel jl_aita;
    private javax.swing.JLabel jl_city;
    private javax.swing.JLabel jl_country;
    private javax.swing.JPanel jp_tabAirport;
    private javax.swing.JPanel jp_updateTabAirport;
    private javax.swing.JTextField jt_aita;
    private javax.swing.JTextField jt_city;
    private javax.swing.JTextField jt_country;
    private javax.swing.JButton pb_delete;
    private javax.swing.JButton pb_reset;
    private javax.swing.JButton pb_update;
    // End of variables declaration//GEN-END:variables
}
