/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Formation
 */
public class InterfaceView extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public InterfaceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpan_toolbar = new javax.swing.JPanel();
        pb_programmedFlight = new javax.swing.JButton();
        pb_waitingFlight = new javax.swing.JButton();
        pb_newFlight = new javax.swing.JButton();
        pb_airports = new javax.swing.JButton();
        pb_newAirports = new javax.swing.JButton();
        pb_users = new javax.swing.JButton();
        pb_newUser = new javax.swing.JButton();
        jpan_Print = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        pb_programmedFlight.setText("vols programmés");

        pb_waitingFlight.setText("vols en attente");

        pb_newFlight.setText("nouveau vol");

        pb_airports.setText("aéroport");

        pb_newAirports.setText("nouvel aéroport");

        pb_users.setText("utilisateur");

        pb_newUser.setText("nouvel utilisateur");

        javax.swing.GroupLayout jpan_toolbarLayout = new javax.swing.GroupLayout(jpan_toolbar);
        jpan_toolbar.setLayout(jpan_toolbarLayout);
        jpan_toolbarLayout.setHorizontalGroup(
            jpan_toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_toolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pb_programmedFlight)
                .addGap(18, 18, 18)
                .addComponent(pb_waitingFlight)
                .addGap(18, 18, 18)
                .addComponent(pb_newFlight)
                .addGap(18, 18, 18)
                .addComponent(pb_airports)
                .addGap(18, 18, 18)
                .addComponent(pb_newAirports)
                .addGap(18, 18, 18)
                .addComponent(pb_users)
                .addGap(18, 18, 18)
                .addComponent(pb_newUser)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jpan_toolbarLayout.setVerticalGroup(
            jpan_toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_toolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpan_toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pb_programmedFlight)
                    .addComponent(pb_waitingFlight)
                    .addComponent(pb_newFlight)
                    .addComponent(pb_airports)
                    .addComponent(pb_newAirports)
                    .addComponent(pb_users)
                    .addComponent(pb_newUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpan_PrintLayout = new javax.swing.GroupLayout(jpan_Print);
        jpan_Print.setLayout(jpan_PrintLayout);
        jpan_PrintLayout.setHorizontalGroup(
            jpan_PrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpan_PrintLayout.setVerticalGroup(
            jpan_PrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpan_toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpan_Print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpan_toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpan_Print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpan_Print;
    private javax.swing.JPanel jpan_toolbar;
    private javax.swing.JButton pb_airports;
    private javax.swing.JButton pb_newAirports;
    private javax.swing.JButton pb_newFlight;
    private javax.swing.JButton pb_newUser;
    private javax.swing.JButton pb_programmedFlight;
    private javax.swing.JButton pb_users;
    private javax.swing.JButton pb_waitingFlight;
    // End of variables declaration//GEN-END:variables
}
